name: macOS Build

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.5.0
  QT_ARCH: clang_64
  ARCHIVE_NAME: YaRXP-macos-arm-latest

jobs:

  build:

    permissions:
      contents: write

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3

    - name: Install aqtinstall
      run: pip3 install --break-system-packages aqtinstall

    - name: Install Qt
      run: |
        aqt install-qt mac desktop $QT_VERSION $QT_ARCH -m qtmultimedia -O $HOME/Qt

    - name: Run qmake
      run: |
        export PATH="$HOME/Qt/$QT_VERSION/$QT_ARCH/bin:$PATH"
        qmake CONFIG+=release YaRXP.pro

    - name: Build
      run: make -j$(sysctl -n hw.logicalcpu)

    - name: Create app bundle and DMG
      run: |
        export PATH="$HOME/Qt/$QT_VERSION/$QT_ARCH/bin:$PATH"
        cd build/release
        macdeployqt YaRXP.app -dmg

    - name: List artifacts
      run: find build/release -type f

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: build/release/YaRXP.dmg

    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-macos"
        prerelease: true
        title: "Automatic macOS Build"
        files: |
          build/release/YaRXP.dmg
